version: '3.9'

services:
  postgres:
    image: postgres:15.4
    container_name: sum-app-db
    environment:
      POSTGRES_DB: sum-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: